set nocompatible

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set noundofile
set nobackup
set backspace=indent,eol,start

filetype plugin indent on
syntax on

set number
set cursorline
highlight CursorLine cterm=NONE
highlight CursorLineNr ctermfg=blue
" Set GitGutter sign column color, it
" fixed the problem that the column has grey background.
highlight SignColumn ctermbg=NONE

set clipboard=unnamedplus   

" Sync every 1000 ms rather than default 4000ms so have
" better experience for GitGutter.
set updatetime=1000
" Always show GitGutter's side bar so won't occasionally
" moves the entire text.
set signcolumn=yes
